# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 柏林反潮流日志
email: lhyssss@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  欢迎来访我的信息收集地。潮流和风口不同，每个人都是一股潮流。
baseurl: "/my-blog" # the subpath of your site, e.g. /blog
url: "https://howareu994.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  my-blog
xiaohongshu_username: 57cf764ca9b2ed36a488dfb8

# Fields minima uses, but not defaulted with the jekyll new command.
# Author is the default for post, the atom feed, and it used in the footer.
author: Howru994
# instagram_username: howutii
# linkedin_username: Howru994

# new fields are not defaulted by jekyll new with the minima theme
# add a copyright. A copyright symbol and year will be added automaticlly.
# copyright: companyname, Inc.
copyright: "Howru"

# Build settings
# Removed minima theme as it is a regular theme.
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
